<a href="https://colab.research.google.com/github/realtechz/Tensorflow_zero_to_mastery/blob/00_TF_fundamentals/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook , we are going to cover some of the most fundamental concepts of tensors usinf Tensorflow

More Specifically , we are going to cover:
* Introduction to tensors
* Getting information from tensors
* Maniplulating tensors
* Tensors and NumPy
* Using @tf.function (a way to speed up your regular python functions)
* Using GPUs with tensorflow ( or TPUs)
* Exercises to try for yourself!

## intro to Tensors

In [89]:
# inmport tensorflow
import tensorflow as tf
print(tf.__version__)

2.5.0


In [90]:
#!pip install --ignore-installed --upgrade tensorflow==2.5.0

In [91]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [92]:
# check the no of dim of a tensor ( ndim stands for number of dimensions)
scalar.ndim

0

In [93]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [94]:
# check the dimension of our vector 
vector.ndim

1

In [95]:
# Create a matrix ( has more than 1 dimension)
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [96]:
matrix.ndim

2

In [97]:
# create another matrix with datatype parameter
another_matrix = tf.constant([[10.,7.],[3.,2.],[8.,9.]], dtype= tf.float16)

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [98]:
# dim of another_matrix
another_matrix.ndim

2

In [99]:
# lets create a tensor
tensor = tf.constant([
                      [[1, 2, 3],[4, 5, 6]],
                      [[7, 8, 9],[10, 11, 12]],
                      [[13, 14, 15],[16, 17, 18]]
                      ])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [100]:
# dim in tensor
tensor.ndim

3

what we've created so far:

* Scalar: a single number
* Vector: a number with direction (e.g wind speed and direction)
* Matrix : a 2-dimensional array of numbers 
* Tensor: an n-dimensional array of numbers (where n can be any number , a 0-dim tensor is a scalar, a 1 dim tensor is a vector)

### Creating tensors with tf.variable

In [101]:
# create the same tensor with tf.Variable ( as above)
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [102]:
# Lets try change one of the elementd in our changeable tensor
#changeable_tensor[0] = 7  # does not work
#changeable_tensor

In [103]:
# how about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [104]:
# lets try change our unchangable tensor
#unchangeable_tensor[0].assign(7) # does not work
#unchangeable_tensor

###Creating random tensors

Random tensors are tensors of some arbitary size which contain random number 

this is done because we have start with random inital weights

In [105]:
# Create two random (but the same ) tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape = (3,2))
random_2 =tf.random.Generator.from_seed(42)
random_2 = random_2.uniform(shape = (3,2))
random_3 =tf.random.Generator.from_seed(42)
random_3 = random_3.normal(shape = (3,2))
random_1, random_2,random_2 ==random_1, random_1 == random_3

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.7493447 , 0.73561966],
        [0.45230794, 0.49039817],
        [0.1889317 , 0.52027524]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor
sometimes data set can be sorted so to avoid problems in learning we shuffle the data

In [106]:
# shuffle a tensor (useful when you want to shuffle your data so the inherent order doesn't effect learning )
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
not_shuffled.ndim

2

In [107]:
# shuffing
tf.random.set_seed(42)
shuffled = tf.random.shuffle(not_shuffled)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]])>

### other ways to make tensors


In [108]:
# a tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [109]:
# create a tensor of all zeroes
tf.zeros([10,10])

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into tensors

the main difference between Numpy arrays and tensorflow tensors is that tensors can be run on GPU computing

In [110]:
# you can also turn NUmPy arrays intp tensors
import numpy as np
numpy_A = np.arange(1,25, dtype =np.int32) # create a Numpy array between 1 and 25 

# X = tf.constant(some_matrix) # capital for matri or tensor
# Y = tf.constant(vector) # non-capital for vector

numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [111]:
# not that total elements is 24 = 2x3x4 so we can use only this in shape or similar like this
A = tf.constant(numpy_A, shape=(2, 3, 4))
B = tf.constant(numpy_A)
C = tf.constant(numpy_A, shape=(8,3))

In [112]:
A, B, C

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])>,
 <tf.Tensor: shape=(8, 3), dtype=int32, numpy=
 array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]])>)

In [113]:
A.ndim, C.ndim

(3, 2)

### Getting info from tensors 

when dealing with tensors you must know them
*   Shape
*   Rank
*   Axis or Dimiension
*   Size



In [114]:
# Create a rank 4 tensor (4 dim)
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [115]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [116]:
rank_4_tensor[0][1]

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [117]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [118]:
2*3*4*5

120

In [119]:
# Get various attributes of our tensor

print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor: ", rank_4_tensor.shape)
print("Elements along the 0 axis :", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor))
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor:  (2, 3, 4, 5)
Elements along the 0 axis : 2
Elements along the last axis: 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor: 120


### Indexing Tensors
Tensors can be indexed just like Python Lists.


In [120]:
some_list = [1,2,3,4]
some_list[:2]

[1, 2]

In [121]:
# GEt the first two elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [122]:
some_list[:1]

[1]

In [123]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [124]:
rank_4_tensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [125]:
rank_4_tensor[:1,:,:1,:1]

<tf.Tensor: shape=(1, 3, 1, 1), dtype=float32, numpy=
array([[[[0.]],

        [[0.]],

        [[0.]]]], dtype=float32)>

In [126]:
# CReate a rank 2 tensor (2 dim)
rank_2_tensor = tf.constant([[1,2],[4,3]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [127]:
#GEt the last item of each row
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3])>

In [128]:
# ADD in extra dim to out rank 2 tensor
# ... represent on every axis before this ignore and add axis to the end 
# s0 ... in this case equals :,:,
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[4],
        [3]]])>

In [129]:
# altenative to tf.newaxis
# -1 axis means on final axis
tf.expand_dims(rank_2_tensor,axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[4],
        [3]]])>

notice the shape to understand where the extra dim is added 

In [130]:
# extra dim in front
tf.expand_dims(rank_2_tensor,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [4, 3]]])>

In [131]:
tf.expand_dims(rank_2_tensor,axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[1, 2]],

       [[4, 3]]])>

### Manipulating Tensor(tensors operations)

**Basic Operations**

`+`,`-`,`*`,`/`


In [132]:
# you can add values using add opp
tensor = tf.constant([[10,7],[8,9]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [18, 19]])>

In [133]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 8,  9]])>

In [134]:
# to change replace it
tensor = tensor + 10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [18, 19]])>

In [135]:
# multiplication also works
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 170],
       [180, 190]])>

In [136]:
# substraction if you want
tensor - 100

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-80, -83],
       [-82, -81]])>

In [137]:
# we can use the tensorflow built in function too # this method will be faster 
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 170],
       [180, 190]])>

***Matrix Multiplication***

Most important and most common tensors

In [138]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [18, 19]])>

In [139]:
tensor * tensor
# tenser x tensor is giving square of a number 
# but we need to use matmul to do matrix multiplication

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[400, 289],
       [324, 361]])>

In [140]:
# Matrix mltiplication in tensorflow
print(tensor)
tf.matmul(tensor,tensor)

tf.Tensor(
[[20 17]
 [18 19]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[706, 663],
       [702, 667]])>

In [141]:
tensor_1 = tf.constant([[1, 2, 5],
                        [7, 2, 1],
                        [3, 3, 3]])
tensor_2 = tf.constant([[3, 5],[6, 7] ,[1, 8]])
tensor_1, tensor_2

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]])>)

In [142]:
# tensor_1 * tensor_2 we cannot do this
tf.matmul(tensor_1, tensor_2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]])>

In [143]:
# matrix mutiplication with python operator '@'
tensor_1 @ tensor_2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]])>

** The dot product**

Matrix multiplication is also referred to as the dot product.
We can perform this in 2 ways:
* `tf.matmul`
* `tf.tensordot`

In [144]:
# Perform the dot product
tf.tensordot(tensor_1, tensor_2, axes= 1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]])>

if the data is not in shape then we could use transpose instead of reshape in matrix multiplication

### Changing the datatype of tensor

In [145]:
# create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [146]:
C = tf.constant([7, 10])
C.dtype

tf.int32

In [147]:
# Change from float 32 bit to 16 bit (reduced precison)
D = tf.cast(B, dtype= tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [148]:
# Change from int32 to float 32
E = tf.cast(C, dtype= tf.float32)
E, E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>,
 tf.float32)

### Aggregating tensors

Aggregating Tensors = condensing them from multiple values down to smaller amount of values

In [149]:
# Get the absolute values
D = tf.constant([-7., 10.])
D

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-7., 10.], dtype=float32)>

In [150]:
# get absolute value
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

Lets go through the following form of aggregation

* Get the min
* Get the max
* Get the mean of a tensor
* Get the sum of tensor

In [151]:
tf.reduce_sum(D), tf.reduce_min(D), tf.reduce_max(D), tf.reduce_mean(D)

(<tf.Tensor: shape=(), dtype=float32, numpy=3.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=-7.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=10.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.5>)

In [152]:
# Create a random tensor with values between 0 and 100 of size 50

In [153]:
np.random.seed(41)
E = tf.constant(np.random.randint(0,100,size=50))
E


<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([64, 35, 12, 98, 80, 65, 89, 23, 85, 26, 56,  3, 35, 50, 70, 84, 86,
       61, 51, 92, 88, 75, 92, 52, 55, 17, 98, 81, 28, 53, 19, 13, 61, 95,
       34, 58,  4, 59,  1, 76, 12, 35,  4, 69, 20,  5, 44, 22, 34, 46])>

In [154]:
tf.size(E), E.ndim, E.shape

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, 1, TensorShape([50]))

In [155]:
tf.reduce_sum(E), tf.reduce_min(E), tf.reduce_max(E), tf.reduce_mean(E)

(<tf.Tensor: shape=(), dtype=int32, numpy=2515>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=98>,
 <tf.Tensor: shape=(), dtype=int32, numpy=50>)

In [156]:
# Find the min
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [157]:
# Find the max
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int32, numpy=98>

In [158]:
# mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=50>

In [159]:
# sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2515>

In [160]:
# variance works in tf 2.5
tf.math.reduce_variance(tf.cast(E, tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=869.81>

In [161]:
tf.__version__

'2.5.0'

### Find the positional max and min

In [162]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [163]:
# finding the max element loc
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [164]:
# finding the min element loc
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [165]:
np.argmax(F)

42

In [166]:
np.argmin(F)

16

In [167]:
# Index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [168]:
# find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [169]:
# check for equality
assert F[tf.argmax(F)] == tf.reduce_max(F)
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

### Squeezing a tensor ( removing all single dimensions)


In [170]:
# CReate a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape = (1, 1, 1, 1, 50))
G, G.shape

(<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
 array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
            0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
            0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
            0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
            0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
            0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
            0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
            0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
            0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
            0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
       dtype=float32)>,
 TensorShape([1, 1, 1, 1, 50]))

In [171]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

### One-hot encoding tensors

In [172]:
# CReate a list of indices
some_list = [0, 1, 2, 3] # could be red , green, blue, purple

# One hot encode our list of indices
tf.one_hot(some_list, depth= len(some_list))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [173]:
# specify custom values for one hot encoding
tf.one_hot(some_list,depth=len(some_list),on_value="x",off_value="o")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'x', b'o', b'o', b'o'],
       [b'o', b'x', b'o', b'o'],
       [b'o', b'o', b'x', b'o'],
       [b'o', b'o', b'o', b'x']], dtype=object)>

### Squaring, log, Square root

In [174]:
# Create a new tensor
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [175]:
# Square root
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [177]:
# Find the squareroot (will error , method requires non-int)
tf.sqrt(tf.cast(H,tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [181]:
# Log
tf.math.log(tf.cast(H,tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### TEnsors and Numpy
Tensorflow interacts beautifully with Numpy 

In [182]:
# Create a tesnor directly from a numpy array
J = tf.constant(np.array([3., 7. , 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [183]:
#covert tensor back to numpy
np.array(J),type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [184]:
# covert tensor J to a numpy
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [185]:
J = tf.constant([3.])
J.numpy()[0]

3.0

In [188]:
# the default types of each array are slightly diffrent
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])
# check datatype
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Finding access to GPUs

In [192]:
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [193]:
!nvidia-smi

Fri Jul  2 19:11:10 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 466.77       Driver Version: 466.77       CUDA Version: 11.3     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0  On |                  N/A |
| N/A   55C    P8    16W /  N/A |   7081MiB /  8192MiB |     33%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------